package com.hang.man.game.util;

import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

/**
 * words moment
 * (these are randomly generated, I'm praying they're appropriate.
 */
public class WordUtil {

    public static final transient List<String> WORD_CHOICES = Arrays.asList("""
            ornery
            choused
            cursorinesses
            agglutinogen
            nonrecombinant
            hodaddies
            deceased
            frogeyes
            bitterest
            motorless
            domestic
            bullmastiff
            nettlers
            dispiteous
            loincloths
            unstoppably
            stillborns
            rotameter
            fingernail
            semimonthly
            compulsiveness
            talebearings
            ay
            confirmand
            trippet
            quadrilaterals
            mool
            externality
            peduncles
            sannop
            floodwalls
            hanselling
            regenerating
            mod
            dentate
            diplexer
            egotist
            punky
            fugatos
            rhinitides
            aquarellist
            blowfish
            aphonic
            fallalery
            notify
            progresses
            dogmatizer
            pasodobles
            protuberantly
            augustly
            abstaining
            neorealist
            salesclerk
            tumorigenicity
            semiabstraction
            cowskin
            cream
            dialectal
            carcinoma
            obtunded
            druidisms
            fireproofed
            digresses
            beseeching
            follower
            photochemical
            mislights
            augmentation
            buckler
            pentathlete
            yessing
            obnubilations
            dorser
            skybridges
            artiest
            sumo
            bechalk
            headships
            malapropists
            sanctifications
            blush
            juicily
            reanalyzes
            comports
            leafless
            snowslides
            cartoned
            psychics
            reorganizer
            tailgates
            oldy
            oversoon
            absorptions
            sightlessness
            janglers
            drawerfuls
            interfused
            pugginesses
            unkenneling
            flagellantism
            punt
            phytogenies
            obviates
            moonstones
            bedders
            doomily
            cyclohexanone
            halazone
            impotent
            jags
            encampments
            inflexibleness
            bucklering
            greased
            philistinisms
            scouts
            inkiest
            trustfulness
            baffled
            darkness
            lieutenants
            maturer
            retsinas
            reckless
            agapes
            topworked
            menacer
            barware
            backwaters
            municipalizing
            tigrish
            tugless
            gherkins
            moo
            sprains
            accusatory
            silvicultural
            sanitations
            foetuses
            multichain
            selectively
            proinsulin
            speleologists
            inaugurals
            addressees
            unthink
            sliced
            mechanizations
            caller
            paroles
            tenebrae
            kilovolt
            philhellene
            coffle
            talars
            insolents
            natter
            sufflating
            elementary
            larynges
            pralltrillers
            jockstrap
            narrates
            thrawn
            tortricid
            selamlik
            swash
            celestials
            publishing
            huswife
            fornices
            depravities
            outboasting
            enmeshment
            proverb
            snazziest
            gas
            transit
            volutins
            geums
            clinkered
            programings
            pliocene
            unhandiness
            moondusts
            seisms
            preterit
            subvocalize
            dissociating
            bouillon
            belting
            ambulatorily
            highbrows
            premiss
            zoogenous
            tyrosines
            kabalism
            regrinding
            unkeeled
            queenships
            gentled
            offenses
            mushinesses
            natured
            cornichon
            ventriloquy
            bemires
            trio
            detesters
            latrine
            successively
            recorders
            lothario
            proponed
            cuttable
            provenly
            misassayed
            sorrowfulness
            cirque
            flight
            mandarinates
            affixments
            emblematize
            underdosed
            outgeneraled
            optimalities
            masquerading
            filoplumes
            nonevent
            diffusively
            personnel
            tailfin
            oxygenated
            plasmalemmas
            centring
            triptane
            loosing
            proboscideans
            deys
            tubbing
            shiva
            colloquists
            hamauls
            evacuator
            dowerless
            rebalances
            nifties
            overcooks
            retiringnesses
            spartinas
            ditchers
            japes
            futhorks
            mingles
            isobutanes
            squealing
            deftness
            jiggering
            nickles
            steelier
            soupcon
            creditable
            goatskins
            nagging
            forepaws
            creamier
            puttied
            respirometries
            sparoids
            dorty
            cerise
            prototypically
            ectomeric
            kwashiorkor
            thunk
            memorizing
            tourmaline
            musing
            diplococcus
            coloni
            weightier
            formee
            parging
            multilateralist
            sandflies
            rebodied
            droved
            lumberers
            capaciously
            camerapersons
            knapsacked
            newbies
            outdazzle
            elephantiasis
            mimeos
            redcoats
            wreckings
            unconsidered
            breadnut
            coturnixes
            nonathletic
            trunkful
            dementias
            nonaspirin
            caninity
            waugh
            confronted
            wittingly
            desecrations
            tostada
            erythromycins
            disbandment
            lathworks
            haftorahs
            blottier
            pearl
            pentaploidy
            synovitis
            headlock
            nurses
            lovelornnesses
            acrospire
            drabble
            theorises
            reservoirs
            oriflamme
            disbranched
            horrifying
            boylas
            rapacity
            somewise
            deadbolts
            dears
            prebirths
            chefdoms
            concessional
            undersea
            jackhammered
            hornless
            slumbery
            skyjacked
            playful
            insurgently
            expiators
            backslider
            boasted
            mobocrat
            antigravity
            ahed
            reprehending
            poloists
            megascopically
            uneaten
            flummoxing
            prorogues
            malevolence
            kelpie
            sensuosity
            lysosomes
            remainders
            outlie
            premanufactures
            validity
            linoleum
            steerable
            rasters
            megrims
            flails
            logogriph
            omophagies
            preapproves
            fidgeted
            scooping
            blockier
            emeritae
            deadeye
            renovator
            millrace
            carrotin
            awfullest
            recognitions
            anorexics
            wartless
            superpremiums
            cockeyedly
            stereotypy
            axised
            hopefulnesses
            rectify
            nudicaul
            paternalists
            clawless
            bravoing
            proroguing
            apres
            axonemal
            evades
            arabicizations
            giftwrap
            crushed
            rackfuls
            boldfaces
            krummhorn
            masculinities
            tenderfeet
            blackbirder
            commas
            foundation
            rhyton
            network
            outmastered
            jelutong
            mutational
            hydrobiologies
            doodoos
            pulsator
            fortressed
            antibioses
            frittering
            nonconsumers
            bedrug
            picometres
            polytypic
            upstood
            poulardes
            sarcous
            bullpens
            downpour
            mopoke
            paraffining
            outoffices
            chirm
            psychologizing
            rarefied
            commonality
            knobbier
            phycocyanin
            massiveness
            pretold
            romanticizing
            melancholia
            karaoke
            tussore
            though
            tarp
            unaffluent
            remobilizes
            heartbeat
            apparats
            choroids
            scrawny
            downrightness
            haiks
            psychohistory
            superregional
            scarab
            simperer
            chlordans
            westernmost
            dot
            qualmier
            pulingly
            exhumer
            poisoners
            coper
            punned
            teammate
            applicable
            unshut
            introgressions
            gaining
            bicentric
            demerger
            rechoreographed
            scrivener
            coralbells
            fruitier
            civilianization
            ambeers
            wyted
            tempi
            gravitates
            misthinks
            moujiks
            tollers
            legitimate
            halloos
            treacle
            suprematists
            hemophilia
            branded
            harvestmen
            virginals
            keratinous
            glints
            daishiki
            milfoil
            apperceiving
            reimpositions
            distension  
            """.split("\n"));

    /**
     * @return Get a character from the user.
     */
    public static char getChar() {
        return (new Scanner(System.in).next().charAt(0));
    }


    public static String underlineWord(String f, Object... args) {


        f = String.format(f, args); // get shadowed noob
        if (!OperatingSystems.isWindows()) {
            System.out.println("You're on windows, so console colors won't work for you. Please enjoy this underlined sequence instead.");
            int platformCount = f.length();
            return f + ("\n" + "-".repeat(platformCount));
        } else {
            return new StringMaker().underline(f).toString();
        }
    }

    /**
     * @param what The string to check
     * @return If the string is a single character.
     */
    public static boolean isChar(String what) {
        return what.length() == 1;
    }
    // a character that for some reason just deletes the entire console.
    private static final String CONSOLE_ANNIHILATION = "\033[H\033[2J";

    public static void clearScreen()
    {
        System.out.print(CONSOLE_ANNIHILATION);
        System.out.flush();
    }
}
